# Generated by Django 4.0.5 on 2022-07-18 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HomepageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movieseriescategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
                ('firstepisode', models.CharField(default='', max_length=100)),
                ('lastepisode', models.CharField(default='', max_length=100)),
                ('writtenby', models.CharField(default='', max_length=100)),
                ('releasedate', models.CharField(default='', max_length=100)),
                ('director', models.CharField(default='', max_length=100)),
                ('distributedby', models.CharField(default='', max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('quality', models.CharField(max_length=100)),
                ('image', models.URLField(default='')),
                ('movie', models.URLField(default='')),
                ('trailer', models.URLField(default='')),
                ('duration', models.CharField(default='', max_length=100)),
                ('movietype', models.CharField(default='', max_length=100)),
                ('movieorseries', models.CharField(default='', max_length=100)),
                ('totalseasons', models.CharField(default='', max_length=100)),
                ('genere', models.ManyToManyField(to='app.category')),
                ('homepagecategory', models.ManyToManyField(default='', to='app.homepagecategory')),
                ('movieseriestype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movieseriescategory')),
            ],
        ),
    ]
