# Generated by Django 4.0.5 on 2022-07-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_allseason_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComingSoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('releasedata', models.CharField(default='', max_length=100)),
                ('imageurl', models.URLField(default='')),
            ],
        ),
    ]
