# Generated by Django 4.0.5 on 2022-07-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comingsoon'),
    ]

    operations = [
        migrations.AddField(
            model_name='comingsoon',
            name='trailer',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='comingsoon',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
