# Generated by Django 4.0.5 on 2022-07-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comingsoon_trailer_comingsoon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('rating', models.CharField(default='', max_length=1000)),
                ('runtime', models.CharField(default='', max_length=1000)),
                ('cast', models.CharField(default='', max_length=1000)),
                ('genre', models.CharField(default='', max_length=1000)),
                ('quality', models.CharField(default='', max_length=1000)),
                ('trailer', models.URLField(blank=True, default='', null=True)),
                ('imageurl', models.URLField(blank=True, default='', null=True)),
            ],
        ),
    ]
