# Generated by Django 4.0.5 on 2022-07-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='seasonnumber',
        ),
        migrations.DeleteModel(
            name='Allseason',
        ),
    ]
