# Generated by Django 4.0.5 on 2022-07-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_season_seasonnumber_delete_allseason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allseason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
