# Generated by Django 4.0.5 on 2022-07-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_topten_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='cast',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
