# Generated by Django 4.0.5 on 2022-07-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_display_cast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='cast',
        ),
    ]
