# Generated by Django 4.0.5 on 2022-07-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_display_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='seasons',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
