# Generated by Django 4.0.5 on 2022-07-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_display_seasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='homepagecategory',
            field=models.ManyToManyField(blank=True, default='', null=True, to='app.homepagecategory'),
        ),
    ]
